---
abstract: 'Crypt::DH Using GMP Directly'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >> '
build_requires:
  Devel::CheckLib: '0.4'
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::Requires: 0
configure_requires:
  Devel::CheckLib: '0.4'
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 3.18
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-DH-GMP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XSLoader: 0.02
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/lestrrat/Crypt-DH-GMP
version: '0.00012'
